export interface Cover {
  readonly file: string;
  readonly eyebrow: string;
  readonly l1: string;
  readonly l2: string;
  readonly l2pre?: string;
  readonly sub: string;
  readonly stats: [string, string, string];
}

export const covers: readonly Cover[] = [
  {
    file: 'og-image',
    eyebrow: 'job queue · SQLite or PostgreSQL',
    l1: 'One file.',
    l2pre: 'Many ',
    l2: 'brokers.',
    sub: 'Memory or one-file SQLite. PostgreSQL 15–18 when you scale. No Redis.',
    stats: ['186K on-disk', 'PostgreSQL 15–18', 'MIT'],
  },
  {
    file: 'og/getting-started',
    eyebrow: 'quickstart',
    l1: 'Working queue',
    l2pre: 'in ',
    l2: 'a minute.',
    sub: 'bun add bunqueue, write ten lines, run. Nothing to provision.',
    stats: ['1 dependency', 'native Bun APIs', 'zero config'],
  },
  {
    file: 'og/queue',
    eyebrow: 'queue api',
    l1: 'Every job, exactly',
    l2pre: 'where it ',
    l2: 'belongs.',
    sub: 'Priorities, delays, deduplication, bulk and durable writes.',
    stats: ['idempotent IDs', 'auto-batching', 'BullMQ-familiar'],
  },
  {
    file: 'og/worker',
    eyebrow: 'workers',
    l1: 'Pull, process,',
    l2pre: 'ack, ',
    l2: 'repeat.',
    sub: 'Concurrency, heartbeats, stall detection, ACK batching.',
    stats: ['long polling', 'lock ownership', 'typed events'],
  },
  {
    file: 'og/server-mode',
    eyebrow: 'server mode',
    l1: 'One protocol,',
    l2pre: 'many ',
    l2: 'brokers.',
    sub: 'SQLite for one broker. PostgreSQL for an active fleet.',
    stats: ['TCP :6789', 'PostgreSQL 15–18', 'native TLS'],
  },
  {
    file: 'og/client-sdk',
    eyebrow: 'sdks',
    l1: 'One protocol,',
    l2pre: 'every ',
    l2: 'runtime.',
    sub: 'Queue and Worker clients for TypeScript, Python, PHP, Go, Rust and Elixir.',
    stats: ['6 official SDKs', 'protocol v3', 'typed'],
  },
  {
    file: 'og/api-reference',
    eyebrow: 'api reference',
    l1: 'Every endpoint,',
    l2pre: '',
    l2: 'documented.',
    sub: 'TCP commands, HTTP routes and every type, spelled out.',
    stats: ['40+ commands', 'msgpack wire', 'JSON HTTP'],
  },
  {
    file: 'og/benchmarks',
    eyebrow: 'benchmarks',
    l1: 'Measured,',
    l2pre: 'not ',
    l2: 'mixed.',
    sub: 'Fresh native processes, distributions, integrity and exact workload labels.',
    stats: ['186K on-disk', '159K TCP PUSHB', '3.2K TCP workflows'],
  },
  {
    file: 'og/integrations',
    eyebrow: 'integrations',
    l1: 'Plays well with',
    l2pre: 'your ',
    l2: 'stack.',
    sub: 'Hono, Elysia, MCP for AI agents, Prometheus, webhooks, S3.',
    stats: ['75 MCP tools', 'SSE + WebSocket', 'Prometheus'],
  },
  {
    file: 'og/advanced',
    eyebrow: 'advanced',
    l1: 'Sagas, cron,',
    l2pre: 'rate limits, ',
    l2: 'DLQ.',
    sub: 'Workflow engine with compensation, everything operational.',
    stats: ['saga rollback', 'cron + tz', 'S3 backups'],
  },
  {
    file: 'og/use-cases',
    eyebrow: 'production patterns',
    l1: 'What teams',
    l2pre: 'run ',
    l2: 'on it.',
    sub: 'Email, webhooks, payments, images, AI agents, cron.',
    stats: ['12+ patterns', 'saga rollback', '75 MCP tools'],
  },
  {
    file: 'og/workflow',
    eyebrow: 'workflow engine',
    l1: 'Multi-step, with',
    l2pre: 'a ',
    l2: 'rollback plan.',
    sub: 'Saga compensation, branching, signals and loops.',
    stats: ['11 event types', 'waitFor signals', '0 extra services'],
  },
  {
    file: 'og/production',
    eyebrow: 'guide · production',
    l1: 'What survives',
    l2pre: '',
    l2: 'a crash.',
    sub: 'At-least-once semantics. SQLite snapshots or PostgreSQL PITR.',
    stats: ['SIGKILL tested', 'fenced ACKs', 'S3 snapshots'],
  },
  {
    file: 'og/hono',
    eyebrow: 'integrations · hono',
    l1: 'Background jobs',
    l2pre: 'for ',
    l2: 'Hono.',
    sub: 'Return the response now, do the work in the background.',
    stats: ['embedded mode', 'zero config', 'typed'],
  },
  {
    file: 'og/elysia',
    eyebrow: 'integrations · elysia',
    l1: 'Background jobs',
    l2pre: 'for ',
    l2: 'Elysia.',
    sub: 'Return the response now, do the work in the background.',
    stats: ['embedded mode', 'zero config', 'typed'],
  },
];
